%YAML:1.0

image_width: 1024
image_height: 768
num_pairs: 1

#================================ Camera Calibrations Settings ================================

## Each matrix below takes a point from the imu frame -> camera frame
extrinsics: 
  - left: !!opencv-matrix  
      rows: 4
      cols: 4
      dt: d
      data: [0.0, 1.0, 0.0, 0.05,
            0.0, 0.0, 1.0, 0.0,
            1.0, 0.0, 0.0, 0.0,
            0.0, 0.0, 0.0, 1.0]


    right: !!opencv-matrix
      rows: 4
      cols: 4
      dt: d
      data: [0.0, 1.0, 0.0, -0.05,
            0.0, 0.0, 1.0, 0.0,
            1.0, 0.0, 0.0, 0.0,
            0.0, 0.0, 0.0, 1.0]


T_W_imu: !!opencv-matrix
  rows: 4
  cols: 4
  dt: d
  data: [1,0,0,0, 0,1,0,0, 0,0,1,0, 0,0,0,1]

intrinsics: 
  - left: !!opencv-matrix  
      rows: 1
      cols: 4
      dt: d
      data: [665.107510106, 665.107510106, 511.5, 383.5]
    right: !!opencv-matrix
      rows: 1
      cols: 4
      dt: d
      data: [665.107510106, 665.107510106, 511.5, 383.5]

distortion_coeffs: 
  - left: !!opencv-matrix  
      rows: 1
      cols: 4
      dt: d
      data: [0, 0, 0, 0]
    right: !!opencv-matrix
      rows: 1
      cols: 4
      dt: d
      data: [0,  0, 0, 0]

#================================ IMU Params ================================
sigma_a: 2.0e-2
sigma_g: 1.6968e-3
sigma_ba: 3.0e-2
sigma_bg: 1.9393e-3
preint_cov: 1.0e-3
preint_bias_cov: 1.0e-5


#================================ Camera Noise Params ================================
sigma_pixel: 1

#================================ Optimization Params ================================
max_iter: 5
abs_tol: 1.0e-3
rel_tol: 1.0e-3
propagateAtImuRate: 0
keyframe_spacing: 0.08

#================================ Debug Params ================================
# To take features from a single pair, specify the pair number. If negative, backend will operate in multi-camera mode
add_features: -1

#================================ Frontend Params ================================
ransac_threshold: 1
num_features: 100
min_dist: 30
pyramid_levels: 3
patch_size: 21
grid_row: 4
grid_col: 5
grid_min_feature_num: 3
grid_max_feature_num: 7

#================================ ROS Topics ================================
imu_topic: "/blackbird/imu"
image_topics:
  - left: "/uav/camera/Camera_Left_Gray/image_rect"
    right: "/uav/camera/Camera_Right_Gray/image_rect"

visulize_pub_topic: "stereo_visualize_img"

